AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  regularly clean cloudwatch logs log group serverless app
  https://github.com/itooww/cloudwatch-logs-cleaner

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  CleanerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cleaner/
      Handler: app.lambda_handler
      Runtime: python3.6
      Tracing: Active
      Role: !GetAtt CleanerFunctionIamRole.Arn
      Events:
        DailyCleanEvent:
          Type: Schedule
          Properties:
            Schedule: rate(6 hours)

  CleanerFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        -
          PolicyName: "minimum_lambda_basic_execution_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
        -
          PolicyName: "use_x-ray_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "xray:PutTraceSegments"
                  - "xray:PutTelemetryRecords"
                  - "xray:GetSamplingRules"
                  - "xray:GetSamplingTargets"
                  - "xray:GetSamplingStatisticSummaries"
                Resource: "*"
        -
          PolicyName: "cleaner_need_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:DescribeLogGroups"
                  - "logs:DeleteLogGroup"
                  - "lambda:ListFunctions"
                  - "apigateway:GET"
                Resource: "*"

Outputs:
  CleanerFunction:
    Description: "Cleaner Lambda Function ARN"
    Value: !GetAtt CleanerFunction.Arn

  CleanerFunctionIamRole:
    Description: "Atattched IAM Role ARN"
    Value: !GetAtt CleanerFunctionIamRole.Arn